### ISSUE TITLE
dplyr v1.0.0 / vctrs todo

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fabletools#192]
Many changes are required to support the upcoming release of dplyr, these issues are consolidated here:

- [x] Use progressr instead of dplyr::progress_estimated() #184
- [x] Improve dplyr methods for mable objects #179
- [x] Automatically select() key variables in a mable #170
- [x] Add support for join operations #161
- [x] Add ggplot2 scales for agg_key structure #141
- [x] Add multivariate functionality back with new distribution structures
